-- AlterTable
ALTER TABLE "Contact" ALTER COLUMN "Mail" SET DEFAULT '',
ALTER COLUMN "Fecha_Creacion" SET DEFAULT 0,
ALTER COLUMN "new_utm_campaign" SET DEFAULT '',
ALTER COLUMN "new_utm_content" SET DEFAULT '',
ALTER COLUMN "new_utm_medium" SET DEFAULT '',
ALTER COLUMN "new_utm_source" SET DEFAULT '',
ALTER COLUMN "new_utm_term" SET DEFAULT '',
ALTER COLUMN "new_utmsname" SET DEFAULT '',
ALTER COLUMN "Estado_Interes" SET DEFAULT '',
ALTER COLUMN "Pais" SET DEFAULT '',
ALTER COLUMN "Linea_Producto" SET DEFAULT '',
ALTER COLUMN "Tipo_Producto" SET DEFAULT '',
ALTER COLUMN "Programa" SET DEFAULT '',
ALTER COLUMN "utm_campaign_contacto" SET DEFAULT '',
ALTER COLUMN "utm_content_contacto" SET DEFAULT '',
ALTER COLUMN "utm_medium_contacto" SET DEFAULT '',
ALTER COLUMN "utm_source_contacto" SET DEFAULT '',
ALTER COLUMN "utm_term_contacto" SET DEFAULT '',
ALTER COLUMN "Estado_Venta" SET DEFAULT '',
ALTER COLUMN "Importe_Venta" SET DEFAULT 0;
